Add new standard for Global Quarantine Notification Interval
KelvinTegelaar/CIPP-API pull request #794
Opened 2024-05-02 18:56 UTC by kris6673

API part for https://github.com/KelvinTegelaar/CIPP/pull/2397

2024-05-02 21:16 UTC, JohnDuprey commented
close for hotfix

2024-05-03 07:17 UTC, OfficialEsco requested changes
They have added $true check for these since https://github.com/KelvinTegelaar/CIPP-API/pull/787 (which makes sense if it comes back as $false)

2024-05-03 07:17 UTC, OfficialEsco commented on Modules/CIPPCore/Public/Standards/Invoke-CIPPStandardGlobalQuarantineNotifications.ps1
> +    if ($Settings.remediate) {
```suggestion
    if ($Settings.remediate -eq $true) {
```

2024-05-03 07:17 UTC, OfficialEsco commented on Modules/CIPPCore/Public/Standards/Invoke-CIPPStandardGlobalQuarantineNotifications.ps1
> +    if ($Settings.alert) {
```suggestion
    if ($Settings.alert -eq $true) {
```

2024-05-03 07:17 UTC, OfficialEsco commented on Modules/CIPPCore/Public/Standards/Invoke-CIPPStandardGlobalQuarantineNotifications.ps1
> +    if ($Settings.report) {
```suggestion
    if ($Settings.report -eq $true) {
```

2024-05-03 07:46 UTC, kris6673 commented
@OfficialEsco Must have missed that somehow, thanks!

2024-05-03 07:49 UTC, OfficialEsco commented
2 days ago tho, just noticed it because of a merge conflict :smile:

2024-05-03 09:30 UTC, KelvinTegelaar commented
Correct, brand spanking new :)

2024-05-03 09:42 UTC, merged

2024-05-03 09:42 UTC, KelvinTegelaar commented
Thanks guys! Great work.

2024-05-03 09:45 UTC, kris6673 commented
> Thanks guys! Great work.

Just ignore line 19 to 27 🤡

2024-05-03 09:47 UTC, KelvinTegelaar commented
hahahaha, so to explain that one, as MS doesn't: PT time is what the Defender and Graph APIs use to define a timespan without needing to do math yourself. They use this in a couple of places where it's just easier to have them figure it out.

2024-05-03 23:45 UTC, kris6673 commented
> hahahaha, so to explain that one, as MS doesn't: PT time is what the Defender and Graph APIs use to define a timespan without needing to do math yourself. They use this in a couple of places where it's just easier to have them figure it out.

Oh that makes sense to save on computing wherever you can
If you can think of a better way to parse it, do let me know ^^